DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS prices;

CREATE TABLE brand(
 ID INT NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(50) NOT NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE prices(
    BRAND_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PRICE_LIST INT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRIORITY INT,
    PRICE FLOAT,
    CURR VARCHAR(3),
    PRIMARY KEY (PRICE_LIST),
    CONSTRAINT FK_Brand_Id FOREIGN KEY (BRAND_ID) REFERENCES brand(ID)
);

